title: Grupo Folclórico Ucraniano Tchóven
description: "Celebre conosco os 25 anos de cultura e dança ucraniana em São José dos Pinhais."

navigation:
  - title: Início
    url: /
  - title: Sobre & História
    url: /sobre.html
  - title: Eventos
    url: /eventos.html
  - title: Apoiadores & Contato
    url: /contato.html

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md