title: Grupo Folclórico Ucraniano Tchóven
description: "Celebre conosco os 25 anos de cultura e dança ucraniana em São José dos Pinhais."

# Estrutura de Navegação - edite os links aqui em um só lugar!
navigation:
  - title: Início
    url: /index.html
  - title: Sobre & História
    url: /sobre.html
  - title: Eventos
    url: /eventos.html
  - title: Apoiadores & Contato
    url: /contato.html

# Exclui arquivos/pastas que o Jekyll não precisa processar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md