title: Grupo Folclórico Ucraniano Tchóven
description: "Celebre conosco os 25 anos de cultura e dança ucraniana em São José dos Pinhais."
permalink: pretty

navigation:
  - title: Início
    url: /
  - title: Sobre & História
    url: /sobre-e-historia/
  - title: Eventos
    url: /eventos/
  - title: Apresentações
    url: /apresentacoes/
  - title: Galeria
    url: /galeria/
  - title: Notícias
    url: /noticias/
  - title: Apoiadores & Contato
    url: /apoiadores-e-contato/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md