title: Grupo Folclórico Ucraniano Tchóven
description: "Celebre conosco os 25 anos de cultura e dança ucraniana em São José dos Pinhais."

# Estrutura de Navegação
navigation:
  - title: Início
    url: /
  - title: Sobre & História
    url: /sobre.html
  - title: Eventos
    url: /eventos.html
  - title: Apresentações      # <-- NOVA LINHA
    url: /apresentacoes.html  # <-- NOVA LINHA
  - title: Apoiadores & Contato
    url: /contato.html

# Exclui arquivos que o Jekyll não precisa processar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md